//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class anterior_abono
    {
        public Nullable<int> cantidad { get; set; }
        public string descripcion { get; set; }
        public string subdescripcion { get; set; }
        public Nullable<decimal> valor_prenda { get; set; }
        public Nullable<decimal> prestamo { get; set; }
        public Nullable<int> registro { get; set; }
        public Nullable<int> folio_contrato { get; set; }
        public string origen { get; set; }
        public string caja { get; set; }
        public int no { get; set; }
    }
}
