//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartados_confg
    {
        public int no { get; set; }
        public string Nombre_plazo { get; set; }
        public Nullable<int> dias { get; set; }
        public Nullable<decimal> apartado_natural { get; set; }
        public Nullable<decimal> apartado_minimo { get; set; }
        public Nullable<int> dias_tolerancia { get; set; }
        public Nullable<int> dias_minimo { get; set; }
        public Nullable<decimal> penalizacion { get; set; }
        public Nullable<decimal> cancelacion { get; set; }
        public Nullable<int> ACTIVADO { get; set; }
    }
}
