//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartadosEspecialesConfig
    {
        public int Id { get; set; }
        public Nullable<decimal> penalizacion { get; set; }
        public Nullable<decimal> minimoConsumo { get; set; }
        public Nullable<int> anos { get; set; }
        public Nullable<int> meses { get; set; }
        public Nullable<int> dias { get; set; }
        public Nullable<decimal> costoReimp { get; set; }
        public Nullable<int> reimpGratisXano { get; set; }
    }
}
