//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartadosEspecialesInventario
    {
        public int Id { get; set; }
        public string inventario { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
        public string folio { get; set; }
    }
}
