//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartadosEspeciales
    {
        public int Id { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string NombreCliente { get; set; }
        public string Huella { get; set; }
        public Nullable<decimal> Meta { get; set; }
        public Nullable<decimal> Acumulado { get; set; }
        public string FolioApartado { get; set; }
        public Nullable<int> DiasMeta { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> FechaApartado { get; set; }
        public Nullable<System.DateTime> FechaCancelado { get; set; }
        public Nullable<System.DateTime> UltimaFechaRetiro { get; set; }
    }
}
