//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartadosEspeciales
    {
        public int Id { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string NombreCliente { get; set; }
        public string Huella { get; set; }
        public Nullable<decimal> Meta { get; set; }
        public Nullable<decimal> Acumulado { get; set; }
        public string FolioApartado { get; set; }
        public Nullable<int> DiasMeta { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> FechaApartado { get; set; }
        public Nullable<System.DateTime> FechaCancelado { get; set; }
        public Nullable<System.DateTime> UltimaFechaRetiro { get; set; }
    }
}
