//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartadosEspecialesConfig
    {
        public int Id { get; set; }
        public Nullable<decimal> penalizacion { get; set; }
        public Nullable<decimal> minimoConsumo { get; set; }
        public Nullable<int> anos { get; set; }
        public Nullable<int> meses { get; set; }
        public Nullable<int> dias { get; set; }
        public Nullable<decimal> costoReimp { get; set; }
        public Nullable<int> reimpGratisXano { get; set; }
    }
}
