//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtPromocionesMovs
    {
        public int Id { get; set; }
        public string Inventario { get; set; }
        public int Cantidad { get; set; }
        public int Entrada { get; set; }
        public int Salida { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Hora { get; set; }
        public string Registro { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<decimal> PrecioPuntos { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string Cliente { get; set; }
        public string Caja { get; set; }
        public string Comentario { get; set; }
        public string Status { get; set; }
        public string Folio { get; set; }
    }
}
