//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtventasAvances
    {
        public int IdArtventasAvances { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Sucursal { get; set; }
        public int NoSemana { get; set; }
        public int CantidadJoyeria { get; set; }
        public decimal ImporteJoyeria { get; set; }
        public int CantidadAutos { get; set; }
        public decimal ImporteAutos { get; set; }
        public int CantidadElectronicos { get; set; }
        public decimal ImporteElectronicos { get; set; }
        public int CantidadElectrodomesticos { get; set; }
        public decimal ImporteElectrodomesticos { get; set; }
        public int CantidadComputo { get; set; }
        public decimal ImporteComputo { get; set; }
        public int CantidadHerramientas { get; set; }
        public decimal ImporteHerramientas { get; set; }
        public int CantidadVideojuegos { get; set; }
        public decimal ImporteVideojuegos { get; set; }
        public int CantidadOtros { get; set; }
        public decimal ImporteOtros { get; set; }
        public int CantidadCelulares { get; set; }
        public decimal ImporteCelulares { get; set; }
        public int CantidadPlata { get; set; }
        public decimal ImportePlata { get; set; }
        public int CantidadTotal { get; set; }
        public decimal ImporteTotal { get; set; }
    }
}
