//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtventasTiempoAvances
    {
        public int IdArtventasTiempo { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Sucursal { get; set; }
        public int NoSemana { get; set; }
        public string Tipo { get; set; }
        public int CantidadPrimerRonda { get; set; }
        public decimal ImportePrimerRonda { get; set; }
        public int CantidadSegundaRonda { get; set; }
        public decimal ImporteSegundaRonda { get; set; }
        public int CantidadTercerRonda { get; set; }
        public decimal ImporteTercerRonda { get; set; }
        public int CantidadTotal { get; set; }
        public decimal ImporteTotal { get; set; }
        public Nullable<decimal> primerRemate { get; set; }
        public Nullable<decimal> segundoRemate { get; set; }
        public Nullable<decimal> tercerRemate { get; set; }
    }
}
