//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtventasEstatusAvances
    {
        public int IdArtventasEstatus { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Sucursal { get; set; }
        public int NoSemana { get; set; }
        public string Tipo { get; set; }
        public int CantidadVENDIDO { get; set; }
        public decimal ImporteVENDIDO { get; set; }
        public int CantidadRECUPERADO { get; set; }
        public decimal ImporteRECUPERADO { get; set; }
        public int CantidadENTRANSITO { get; set; }
        public decimal ImporteENTRANSITO { get; set; }
        public int CantidadTRANSFERIDO { get; set; }
        public decimal ImporteTRANSFERIDO { get; set; }
        public int CantidadAPARTADO { get; set; }
        public decimal ImporteAPARTADO { get; set; }
        public int CantidadENVENTA { get; set; }
        public decimal ImporteENVENTA { get; set; }
        public int CantidadTotal { get; set; }
        public decimal ImporteTotal { get; set; }
    }
}
