//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class artventas901
    {
        public string no { get; set; }
        public Nullable<int> contrato { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> bolsa { get; set; }
        public string noinv { get; set; }
        public string noserie { get; set; }
        public string descripcion { get; set; }
        public string detalles { get; set; }
        public Nullable<decimal> preciosugerido { get; set; }
        public Nullable<decimal> precioventa { get; set; }
        public string kilates { get; set; }
        public string peso_real { get; set; }
        public string condiciones { get; set; }
        public string tipo { get; set; }
        public string status { get; set; }
        public int mov { get; set; }
        public Nullable<System.DateTime> rematado { get; set; }
        public string rematado_por { get; set; }
        public string mod_extemporanea { get; set; }
        public string transferido { get; set; }
        public string sucursal { get; set; }
        public string status_transferido { get; set; }
        public Nullable<System.DateTime> fecha_trans { get; set; }
        public Nullable<System.DateTime> actualizacion { get; set; }
        public string codigotrans { get; set; }
        public string pneto { get; set; }
        public string NOTAS { get; set; }
        public string AOM { get; set; }
        public Nullable<System.DateTime> rematadoEJ { get; set; }
        public Nullable<decimal> precio_promocion { get; set; }
    }
}
