//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditoria_fisica
    {
        public int no { get; set; }
        public Nullable<int> contrato { get; set; }
        public Nullable<decimal> prendas { get; set; }
        public string encontrado { get; set; }
        public string detalles { get; set; }
        public string tipo { get; set; }
        public string prendas_sistema { get; set; }
        public string status_contrato { get; set; }
        public Nullable<System.DateTime> fecha_contrato { get; set; }
        public string audito { get; set; }
        public string superviso { get; set; }
        public Nullable<System.DateTime> fecha_auditoria { get; set; }
        public string localidad { get; set; }
        public string diferencia { get; set; }
    }
}
