//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int no { get; set; }
        public Nullable<int> Valor { get; set; }
        public string Concepto { get; set; }
        public string Procedimiento { get; set; }
        public string Area { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
    }
}
