//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class autorizaciones_prestamos
    {
        public int no { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public string usuario { get; set; }
        public Nullable<decimal> anterior { get; set; }
        public Nullable<decimal> nuevo { get; set; }
        public string motivo { get; set; }
        public string paraelcontrato { get; set; }
    }
}
