//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class bolsas_ORO
    {
        public Nullable<int> Contrato { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Bolsa { get; set; }
        public string Descripcion { get; set; }
        public string SubDescripcion { get; set; }
        public string Kilates { get; set; }
        public string PesoReal { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Avaluo { get; set; }
        public Nullable<decimal> Prestamo { get; set; }
        public string EstatusPrenda { get; set; }
        public string Cantidad { get; set; }
        public string Localidad { get; set; }
        public string Ubicacion { get; set; }
        public string Posicion { get; set; }
        public string registro { get; set; }
        public string folio { get; set; }
        public string origen { get; set; }
        public int INT { get; set; }
        public string condiciones { get; set; }
        public string caja { get; set; }
        public string pneto { get; set; }
    }
}
