//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BolsasOtroes
    {
        public int Int { get; set; }
        public Nullable<int> Contrato { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Bolsa { get; set; }
        public string Descripcion { get; set; }
        public string SubDescripcion { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Avaluo { get; set; }
        public string EstatusPrenda { get; set; }
        public string Condiciones { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Localidad { get; set; }
        public string Ubicacion { get; set; }
        public string Posicion { get; set; }
        public string Sucursal { get; set; }
        public string Registro { get; set; }
        public string No { get; set; }
        public string Folio { get; set; }
        public string Origen { get; set; }
        public Nullable<decimal> Prestamo { get; set; }
        public string Detalles { get; set; }
        public string Caja { get; set; }
        public string DetallesArt { get; set; }
        public string Modelo { get; set; }
        public string Noserie { get; set; }
    }
}
