//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class caja1
    {
        public string plazo { get; set; }
        public Nullable<double> CONTRATO { get; set; }
        public Nullable<double> BOLSA { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<double> Kt { get; set; }
        public Nullable<double> Grs { get; set; }
        public string C__ { get; set; }
        public string Inventario { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<double> PRECIO_1 { get; set; }
        public string Referencia { get; set; }
        public string PRECIO_2 { get; set; }
        public string PRECIO_3 { get; set; }
        public string Venta { get; set; }
        public string Factura { get; set; }
        public string Utilidad { get; set; }
        public Nullable<double> Prestamo { get; set; }
        public string st { get; set; }
        public Nullable<int> desc { get; set; }
        public Nullable<int> kil { get; set; }
        public Nullable<int> pes { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> agregado { get; set; }
        public int @int { get; set; }
    }
}
