//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJA_AUXILIAR
    {
        public int mov { get; set; }
        public string Caja { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
        public string Concepto { get; set; }
        public string Folio { get; set; }
        public Nullable<decimal> Apartado_no { get; set; }
        public Nullable<decimal> abono { get; set; }
        public Nullable<decimal> abono_acumulado { get; set; }
        public Nullable<decimal> debe { get; set; }
        public Nullable<decimal> haber { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> otros_saldo { get; set; }
        public string usuario { get; set; }
        public string Status { get; set; }
        public string Comentario { get; set; }
        public Nullable<decimal> debe2 { get; set; }
        public Nullable<decimal> haber2 { get; set; }
        public Nullable<decimal> otros_saldo2 { get; set; }
    }
}
