//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class calificacion_aud
    {
        public int no { get; set; }
        public Nullable<int> indice { get; set; }
        public Nullable<int> calificacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> valor { get; set; }
        public string sucursal { get; set; }
        public string encargado { get; set; }
        public string sigla { get; set; }
        public string empresa { get; set; }
        public string audito { get; set; }
        public string detalles { get; set; }
        public string folio { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> valorobtenido { get; set; }
        public string proce { get; set; }
        public string concepto { get; set; }
        public Nullable<int> un { get; set; }
    }
}
