//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class clontabla
    {
        public int mov { get; set; }
        public string Caja { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
        public string Concepto { get; set; }
        public string Folio { get; set; }
        public Nullable<int> Contrato { get; set; }
        public Nullable<decimal> Debe { get; set; }
        public Nullable<decimal> Haber { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string Usuario { get; set; }
        public string Movim { get; set; }
        public string Status { get; set; }
        public string Comentario { get; set; }
    }
}
