//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class comprobaciones
    {
        public int comprobacion_no { get; set; }
        public Nullable<System.DateTime> fecha_comprobacion { get; set; }
        public string codigo_comprobacion { get; set; }
        public string empresa { get; set; }
        public string suc { get; set; }
        public string dir { get; set; }
        public string responsable { get; set; }
        public string superviso { get; set; }
    }
}
