//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_valores_plazos
    {
        public int no { get; set; }
        public string nombre_calendario { get; set; }
        public string valor_en_cantidad { get; set; }
        public string sigla_asignada { get; set; }
        public string variable { get; set; }
    }
}
