//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigNotaPagoPromociones
    {
        public int Id { get; set; }
        public string NombrePromocion { get; set; }
        public System.DateTime VigenciaDel { get; set; }
        public System.DateTime VigenciaAl { get; set; }
        public string TiposAdmitidos { get; set; }
        public int LimiteMaximoDePTS { get; set; }
        public decimal OtorgaPTSxCada { get; set; }
        public int PTS { get; set; }
        public int LimiteMaximoPTSXCadaOp { get; set; }
        public string Status { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Registro { get; set; }
    }
}
