//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_temporal
    {
        public Nullable<int> No { get; set; }
        public string Primer_plazo { get; set; }
        public Nullable<System.DateTime> Fecha_de_pago { get; set; }
        public Nullable<decimal> monto_prestamo { get; set; }
        public Nullable<decimal> Interes { get; set; }
        public Nullable<decimal> Seguro { get; set; }
        public Nullable<decimal> Almacenaje { get; set; }
        public Nullable<decimal> Total_a_pagar { get; set; }
        public Nullable<decimal> Refrendo { get; set; }
        public Nullable<int> Fecha_sistema { get; set; }
        public string contrato { get; set; }
        public string caja { get; set; }
        public Nullable<System.DateTime> fecha_compara { get; set; }
        public int indice { get; set; }
    }
}
