//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoDesempenoC
    {
        public int IdContratoDesemp { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public string Sucursal { get; set; }
        public Nullable<int> NoSemana { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Prestamo { get; set; }
        public Nullable<decimal> ImporteFact { get; set; }
        public Nullable<decimal> IvaFact { get; set; }
        public Nullable<decimal> TotalFact { get; set; }
    }
}
