//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class contabilidad
    {
        public int no { get; set; }
        public string Nombre { get; set; }
        public string Localidad { get; set; }
        public string Caja { get; set; }
        public string Clave { get; set; }
        public string Cuenta_prestamos { get; set; }
        public string Cuenta_caja { get; set; }
        public string Cuenta_interes { get; set; }
        public string Cuenta_iva { get; set; }
        public string departamento { get; set; }
        public string leyenda1 { get; set; }
        public string leyenda2 { get; set; }
        public string leyenda3 { get; set; }
    }
}
