//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratoes
    {
        public int Reg { get; set; }
        public Nullable<int> Folio { get; set; }
        public Nullable<int> Contrato1 { get; set; }
        public string Fecha { get; set; }
        public Nullable<int> Bolsa { get; set; }
        public Nullable<int> IdClientes { get; set; }
        public string Ncliente { get; set; }
        public string AutorizoA { get; set; }
        public string Plazo { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> FechaDesemp { get; set; }
        public string Comentario { get; set; }
        public string Dias { get; set; }
        public Nullable<System.DateTime> FechaCons { get; set; }
        public Nullable<decimal> Prestamo { get; set; }
        public Nullable<double> Interes { get; set; }
        public Nullable<double> Seguro { get; set; }
        public Nullable<double> Almacenaje { get; set; }
        public string Plazo1 { get; set; }
        public string Plazo2 { get; set; }
        public string Plazo3 { get; set; }
        public Nullable<decimal> Avaluo { get; set; }
        public string ValuacionTipo { get; set; }
        public string Cancelado { get; set; }
        public string Comentariocancelado { get; set; }
        public Nullable<decimal> Prestamoprom { get; set; }
        public string Origen { get; set; }
        public string Folioavaluo { get; set; }
        public Nullable<int> Clasificacion { get; set; }
        public string Santerior { get; set; }
        public string Caja { get; set; }
        public string Pension { get; set; }
        public string Rev { get; set; }
        public Nullable<double> Temp { get; set; }
        public string VenOvig { get; set; }
        public string Realizo { get; set; }
        public Nullable<decimal> CobroOriginal { get; set; }
        public string BloqueadoComentario { get; set; }
        public byte[] HuellaCotitular { get; set; }
        public Nullable<int> IdCotitular { get; set; }
    }
}
