//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_SEMP
    {
        public int idCRM_SEMP { get; set; }
        public string LOCALIDAD_NOM { get; set; }
        public Nullable<System.DateTime> FECHA_NOM { get; set; }
        public Nullable<System.TimeSpan> HORA_NOM { get; set; }
        public Nullable<decimal> PRESTAMO_C { get; set; }
        public Nullable<decimal> PRESTAMO_P { get; set; }
        public Nullable<decimal> REFRENDO_C { get; set; }
        public Nullable<decimal> REFRENDO_P { get; set; }
        public Nullable<decimal> REMISION_C { get; set; }
        public Nullable<decimal> REMISION_P { get; set; }
        public Nullable<decimal> APARTADO_C { get; set; }
        public Nullable<decimal> APARTADO_P { get; set; }
        public Nullable<decimal> DEPOSITO_C { get; set; }
        public Nullable<decimal> DEPOSITO_P { get; set; }
        public Nullable<decimal> RETIRO_C { get; set; }
        public Nullable<decimal> RETIRO_P { get; set; }
        public Nullable<decimal> REIMPRESION_C { get; set; }
        public Nullable<decimal> REIMPRESION_P { get; set; }
        public Nullable<decimal> ABONO_C { get; set; }
        public Nullable<decimal> ABONO_P { get; set; }
        public Nullable<decimal> MOVS { get; set; }
        public Nullable<decimal> GASTOS_C { get; set; }
        public Nullable<decimal> GASTOS_P { get; set; }
        public Nullable<decimal> C_AU { get; set; }
        public Nullable<decimal> P_AU { get; set; }
        public Nullable<decimal> C_JOY { get; set; }
        public Nullable<decimal> P_JOY { get; set; }
        public Nullable<decimal> C_ELE { get; set; }
        public Nullable<decimal> P_ELE { get; set; }
        public Nullable<decimal> C_OTR { get; set; }
        public Nullable<decimal> P_OTR { get; set; }
        public Nullable<decimal> C_NR { get; set; }
        public Nullable<decimal> C_ND { get; set; }
    }
}
