//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class depositos
    {
        public int no { get; set; }
        public Nullable<decimal> deposito { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string realizo { get; set; }
        public string caja { get; set; }
        public string comentario { get; set; }
        public string tipo_deposito { get; set; }
    }
}
