//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescManuales
    {
        public int Id { get; set; }
        public string NoInv { get; set; }
        public string Descripcion { get; set; }
        public int Contrato { get; set; }
        public decimal Prestamo { get; set; }
        public decimal PrecioOriginal { get; set; }
        public int DiasEnVenta { get; set; }
        public int NoRemate { get; set; }
        public decimal DescAplicado { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public decimal PrecioRemate { get; set; }
        public string RealizadoPor { get; set; }
        public System.DateTime FechaEntVenta { get; set; }
        public System.DateTime FechaDesc { get; set; }
        public string Comentarios { get; set; }
        public Nullable<bool> Autorizado { get; set; }
        public string AutorizadoPor { get; set; }
        public Nullable<System.DateTime> FechaAutorizado { get; set; }
        public string RechazadoPor { get; set; }
        public Nullable<bool> Rechazado { get; set; }
        public Nullable<System.DateTime> FechaRechazado { get; set; }
        public string ComentariosRechazado { get; set; }
        public string Status { get; set; }
        public int Indice { get; set; }
        public string Tipo { get; set; }
    }
}
