//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class descuentos_distintos
    {
        public int no { get; set; }
        public string folio { get; set; }
        public Nullable<int> contrato { get; set; }
        public Nullable<int> bolsa { get; set; }
        public string idcliente { get; set; }
        public string R_D { get; set; }
        public string tipo_C { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Status_Contrato { get; set; }
        public string tipo_desc { get; set; }
        public Nullable<double> descuento { get; set; }
        public string comentario { get; set; }
        public Nullable<decimal> A_desempeñar { get; set; }
        public Nullable<decimal> D_desempeñar { get; set; }
        public Nullable<decimal> A_refrendar { get; set; }
        public Nullable<decimal> D_refrendar { get; set; }
        public Nullable<decimal> antes_prestamo { get; set; }
        public Nullable<decimal> ahora_prestamo { get; set; }
        public Nullable<decimal> antes_pension { get; set; }
        public Nullable<decimal> ahora_pension { get; set; }
        public Nullable<decimal> antes_resmision { get; set; }
        public Nullable<decimal> ahora_remision { get; set; }
        public string autorizo { get; set; }
        public string caja { get; set; }
        public string status { get; set; }
        public string leyendaPromocion { get; set; }
        public string Status_contrato { get; set; }
    }
}
