//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class efectivoCorte
    {
        public int IdEfectivoCorte { get; set; }
        public string Sucursal { get; set; }
        public string Caja { get; set; }
        public string Hora { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Registro { get; set; }
        public bool Estatus { get; set; }
        public decimal Boveda { get; set; }
        public decimal Mil { get; set; }
        public decimal Quinientos { get; set; }
        public decimal Docientos { get; set; }
        public decimal Cien { get; set; }
        public decimal Cincuenta { get; set; }
        public decimal Veinte { get; set; }
        public decimal VeinteM { get; set; }
        public decimal Diez { get; set; }
        public decimal Cinco { get; set; }
        public decimal Dos { get; set; }
        public decimal Uno { get; set; }
        public decimal CincuentaC { get; set; }
        public decimal VeinteC { get; set; }
        public decimal DiezC { get; set; }
        public decimal CincoC { get; set; }
        public Nullable<int> Cmil { get; set; }
        public Nullable<int> Cquinientos { get; set; }
        public Nullable<int> Cdocientos { get; set; }
        public Nullable<int> Ccien { get; set; }
        public Nullable<int> Ccincuenta { get; set; }
        public Nullable<int> Cveinte { get; set; }
        public Nullable<int> CveinteM { get; set; }
        public Nullable<int> Cdiez { get; set; }
        public Nullable<int> Ccinco { get; set; }
        public Nullable<int> Cdos { get; set; }
        public Nullable<int> Cuno { get; set; }
        public Nullable<int> CcincuentaC { get; set; }
        public Nullable<int> CveinteC { get; set; }
        public Nullable<int> CdiezC { get; set; }
        public Nullable<int> CcincoC { get; set; }
    }
}
