//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadosRepublica
    {
        public int no { get; set; }
        public string Estado { get; set; }
        public string clave { get; set; }
        public string nom { get; set; }
        public Nullable<int> nom2 { get; set; }
    }
}
