//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETQ_VENTA
    {
        public int no { get; set; }
        public string Descripcion { get; set; }
        public string Detalles { get; set; }
        public string kt { get; set; }
        public string Peso { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string tipo { get; set; }
        public string Inventario { get; set; }
        public Nullable<decimal> especial { get; set; }
        public string pr { get; set; }
        public Nullable<decimal> REMATE_UNO { get; set; }
        public Nullable<decimal> REMATE_DOS { get; set; }
        public Nullable<decimal> REMATE_TRES { get; set; }
    }
}
