//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialinventarioPromocion
    {
        public int IdHistorial { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Inventario { get; set; }
        public Nullable<int> Inicio { get; set; }
        public Nullable<int> PorPromocion { get; set; }
        public Nullable<int> Agregados { get; set; }
        public Nullable<int> Restados { get; set; }
        public Nullable<int> Total { get; set; }
        public string Realizo { get; set; }
        public string ComentarioModificacion { get; set; }
    }
}
