//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialinventarioPromocion
    {
        public int IdHistorial { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Inventario { get; set; }
        public Nullable<int> Inicio { get; set; }
        public Nullable<int> PorPromocion { get; set; }
        public Nullable<int> Agregados { get; set; }
        public Nullable<int> Restados { get; set; }
        public Nullable<int> Total { get; set; }
        public string Realizo { get; set; }
        public string ComentarioModificacion { get; set; }
    }
}
