//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventariopromocion
    {
        public Nullable<int> cantidad { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string detalles { get; set; }
        public string imagen { get; set; }
        public Nullable<int> otorgado_por { get; set; }
        public string promocion_q_participa { get; set; }
        public Nullable<decimal> precioxcanje { get; set; }
        public int no { get; set; }
        public string alta_por { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public string no_inv { get; set; }
    }
}
