//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localidades
    {
        public int No { get; set; }
        public string LOCALIDAD { get; set; }
        public string Nombre_Sucursal { get; set; }
        public Nullable<System.DateTime> FECHAALTA { get; set; }
        public string CONCEPTO { get; set; }
        public string ENCARGADO { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string CALLE { get; set; }
        public string COLONIA { get; set; }
        public string NO_int { get; set; }
        public string NO_ext { get; set; }
        public string CP { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string email { get; set; }
        public string Tel_adicional { get; set; }
        public string Bomberos { get; set; }
        public string Seguridad_Publica { get; set; }
        public string Marca { get; set; }
        public string Empresa { get; set; }
        public string Logotipo { get; set; }
        public string Proteccioncivil { get; set; }
        public string XXX { get; set; }
        public Nullable<decimal> objetivoMEs { get; set; }
        public string formato { get; set; }
        public string CAS { get; set; }
        public string lugar_conta { get; set; }
        public string impresora { get; set; }
        public string contador { get; set; }
        public string copia { get; set; }
        public string BD { get; set; }
        public string central { get; set; }
        public string uno { get; set; }
        public Nullable<int> codigo { get; set; }
        public Nullable<int> remformato { get; set; }
        public Nullable<int> NOTADEPAGO { get; set; }
        public Nullable<int> HABILITADO { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public string WhatsApp { get; set; }
    }
}
