//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasDescuento
    {
        public int Id { get; set; }
        public string ND { get; set; }
        public int IdCliente { get; set; }
        public string Cliente { get; set; }
        public string TipOperacion { get; set; }
        public string NP { get; set; }
        public string Remision { get; set; }
        public int Contrato { get; set; }
        public decimal Prestamo { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Iva { get; set; }
        public decimal Total { get; set; }
        public decimal SubTotalR { get; set; }
        public decimal IvaR { get; set; }
        public decimal TotalR { get; set; }
        public string Estatus { get; set; }
        public decimal CantidadDescuento { get; set; }
        public decimal ImporteDescuento { get; set; }
        public string Caja { get; set; }
        public string ArgumentoUsuario { get; set; }
        public string Usuario { get; set; }
        public string JefeAutorizo { get; set; }
        public System.DateTime FechaDescuento { get; set; }
        public string GOAutorizo { get; set; }
        public string GOAutorizado { get; set; }
        public string GOArgumento { get; set; }
        public System.DateTime GOAutorizadoFecha { get; set; }
        public string Auditor { get; set; }
        public string Auditado { get; set; }
        public string AuditorArgumento { get; set; }
        public System.DateTime AuditadoFecha { get; set; }
        public string Sucursal { get; set; }
    }
}
