//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plazos_prestamos
    {
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Interes { get; set; }
        public Nullable<double> Seguro { get; set; }
        public Nullable<double> Almacenaje { get; set; }
        public string Tipo_plazo { get; set; }
        public string Porcentaje_prestamo { get; set; }
        public string Porcentaje_avaluo { get; set; }
        public string Aplica_avaluo { get; set; }
        public string Plazo_1 { get; set; }
        public Nullable<int> Numero_plazo_1 { get; set; }
        public Nullable<int> Repeticiones_1 { get; set; }
        public string Plazo_2 { get; set; }
        public Nullable<int> Numero_plazo_2 { get; set; }
        public Nullable<int> Repeticiones_2 { get; set; }
        public string Plazo_3 { get; set; }
        public Nullable<int> Numero_plazo_3 { get; set; }
        public Nullable<int> Repeticiones_3 { get; set; }
        public string Plazo_4 { get; set; }
        public Nullable<int> Numero_plazo_4 { get; set; }
        public Nullable<int> Repeticiones_4 { get; set; }
        public string Plazo_5 { get; set; }
        public Nullable<int> Numero_plazo_5 { get; set; }
        public Nullable<int> Repeticiones_5 { get; set; }
        public string Plazo_6 { get; set; }
        public Nullable<int> Numero_plazo_6 { get; set; }
        public Nullable<int> Repeticiones_6 { get; set; }
        public string Plazo_7 { get; set; }
        public Nullable<int> Numero_plazo_7 { get; set; }
        public Nullable<int> Repeticiones_7 { get; set; }
        public string Plazo_8 { get; set; }
        public Nullable<int> Numero_plazo_8 { get; set; }
        public Nullable<int> Repeticiones_8 { get; set; }
        public string Plazo_9 { get; set; }
        public Nullable<int> Numero_plazo_9 { get; set; }
        public Nullable<int> Repeticiones_9 { get; set; }
        public string Plazo_10 { get; set; }
        public Nullable<int> Numero_plazo_10 { get; set; }
        public Nullable<int> Repeticiones_10 { get; set; }
        public Nullable<int> Total_plazos { get; set; }
        public string Status_plazo { get; set; }
        public string alta_por { get; set; }
        public string Fecha_alta { get; set; }
        public string no { get; set; }
        public string CAT { get; set; }
        public Nullable<int> dias_gracia { get; set; }
        public string CODIFICACION { get; set; }
        public int Id { get; set; }
    }
}
