//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocionesregalo
    {
        public int no { get; set; }
        public string nombre { get; set; }
        public string activa { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> vigencia_i { get; set; }
        public Nullable<System.DateTime> vigenci_f { get; set; }
    }
}
