//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class promociones_Activas
    {
        public string promociones { get; set; }
        public string activa { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> descuento_porciento { get; set; }
        public Nullable<decimal> descuento_cantidad { get; set; }
        public Nullable<System.DateTime> VIGENCIA { get; set; }
        public string tipo { get; set; }
        public string operacion { get; set; }
        public string tipo_desc { get; set; }
        public Nullable<decimal> compra_mayor_a { get; set; }
        public string DOCUMENTO_REQUERIDO { get; set; }
        public Nullable<int> requeridas { get; set; }
        public Nullable<int> cobrar { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string realizo { get; set; }
        public int @int { get; set; }
    }
}
