//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class prom_aplica
    {
        public int ind { get; set; }
        public Nullable<int> por_cada_pt { get; set; }
        public Nullable<decimal> vale_tipo { get; set; }
        public string tipo { get; set; }
        public string operacion { get; set; }
        public Nullable<System.DateTime> vigencia { get; set; }
        public string activado { get; set; }
    }
}
