//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class promociones
    {
        public int no { get; set; }
        public string folio { get; set; }
        public string concepto { get; set; }
        public Nullable<double> descuento { get; set; }
        public Nullable<decimal> anterior { get; set; }
        public Nullable<decimal> nuevo { get; set; }
        public string inv { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string realizo { get; set; }
        public string clave { get; set; }
        public string caja { get; set; }
        public string suc { get; set; }
    }
}
