//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntosClientes
    {
        public int IdPuntosCliente { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> PtsIniciales { get; set; }
        public Nullable<int> PtsPrestamos { get; set; }
        public Nullable<int> PtsNP { get; set; }
        public Nullable<int> PtsRemisiones { get; set; }
        public Nullable<int> PtsApartados { get; set; }
        public Nullable<int> PtsUsados { get; set; }
        public Nullable<int> PtsTotales { get; set; }
        public string MovRealizadoPor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string NombrePromocion { get; set; }
        public string Operacion { get; set; }
    }
}
