//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class puntos_confg
    {
        public int no { get; set; }
        public string documento { get; set; }
        public string status_contratos { get; set; }
        public string status_NP { get; set; }
        public Nullable<decimal> cantidad_C { get; set; }
        public Nullable<decimal> cantidad_NP { get; set; }
        public Nullable<decimal> valor_pts_C { get; set; }
        public Nullable<decimal> valor_pts_NP { get; set; }
        public Nullable<System.DateTime> vigencia_de { get; set; }
        public Nullable<System.DateTime> vigencia_a { get; set; }
        public string activado { get; set; }
        public string echo_por { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string tipo { get; set; }
        public Nullable<int> ptsxContrato { get; set; }
        public string NombrePromocion { get; set; }
    }
}
