//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroHuellas
    {
        public int IdAutorizacion { get; set; }
        public string Autorizacion { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> NoEmpleado { get; set; }
        public string Nivel { get; set; }
        public byte[] Huella { get; set; }
    }
}
