//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class remate_inventarios
    {
        public int no { get; set; }
        public string tipo { get; set; }
        public Nullable<int> premate { get; set; }
        public Nullable<decimal> desc_primero { get; set; }
        public Nullable<int> sremate { get; set; }
        public Nullable<decimal> desc_segundo { get; set; }
        public Nullable<int> remate { get; set; }
    }
}
