//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class remisiones
    {
        public string NumRemision { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Cliente { get; set; }
        public string Inventario { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Descripcion { get; set; }
        public string conceptopromocion { get; set; }
        public string noserieart { get; set; }
        public string codebar { get; set; }
        public string vendio { get; set; }
        public string suc { get; set; }
        public string status { get; set; }
        public string idcliente { get; set; }
        public string comentarios { get; set; }
        public string caja { get; set; }
        public string tipo_desc { get; set; }
        public string tipo_prenda { get; set; }
        public int consec { get; set; }
        public Nullable<int> noRemate { get; set; }
        public Nullable<decimal> precioRemate { get; set; }
        public Nullable<decimal> descRemate { get; set; }
        public string conceptPromocion { get; set; }
        public Nullable<decimal> descPromocion { get; set; }
        public string tipoDescPromocion { get; set; }
        public string auditado { get; set; }
        public string audita { get; set; }
        public Nullable<System.DateTime> fechaAuditado { get; set; }
        public string comentarioAuditado { get; set; }
        public string autorizado { get; set; }
        public string autoriza { get; set; }
        public Nullable<System.DateTime> fechaAutoriza { get; set; }
        public string comentarioAutorizado { get; set; }
    }
}
