//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saldos
    {
        public int IdSaldos { get; set; }
        public string Caja { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Saldo { get; set; }
    }
}
