//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaldoEnVivoCajas
    {
        public int IdSaldoEnCajas { get; set; }
        public string Sucursal { get; set; }
        public string Caja { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Hora { get; set; }
        public decimal Boveda { get; set; }
        public decimal Documento { get; set; }
        public decimal Saldo { get; set; }
        public decimal TotalEfectivoBoveda { get; set; }
        public double Diferencia { get; set; }
        public decimal Efectivo { get; set; }
    }
}
