//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SEMP2013_Context : DbContext
    {
        public SEMP2013_Context()
            : base("name=SEMP2013_Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArtPromociones> ArtPromociones { get; set; }
        public virtual DbSet<ArtPromocionesMovs> ArtPromocionesMovs { get; set; }
        public virtual DbSet<artventas> artventas { get; set; }
        public virtual DbSet<ArtventasAvances> ArtventasAvances { get; set; }
        public virtual DbSet<ArtventasEstatusAvances> ArtventasEstatusAvances { get; set; }
        public virtual DbSet<ArtventasTiempoAvances> ArtventasTiempoAvances { get; set; }
        public virtual DbSet<bolsas_ORO> bolsas_ORO { get; set; }
        public virtual DbSet<bolsas_OTROS> bolsas_OTROS { get; set; }
        public virtual DbSet<ClientesPtsPromociones> ClientesPtsPromociones { get; set; }
        public virtual DbSet<ConfigGlobalPromociones> ConfigGlobalPromociones { get; set; }
        public virtual DbSet<ConfigNotaPagoPromociones> ConfigNotaPagoPromociones { get; set; }
        public virtual DbSet<ConfigPrestamosPromociones> ConfigPrestamosPromociones { get; set; }
        public virtual DbSet<ConfigRemisionPromociones> ConfigRemisionPromociones { get; set; }
        public virtual DbSet<ContratoDesempeno> ContratoDesempeno { get; set; }
        public virtual DbSet<ContratoDesempenoC> ContratoDesempenoC { get; set; }
        public virtual DbSet<ContratoDesempenoCM> ContratoDesempenoCM { get; set; }
        public virtual DbSet<ContratoDesempenoMensuals> ContratoDesempenoMensuals { get; set; }
        public virtual DbSet<contratos> contratos { get; set; }
        public virtual DbSet<CRM_SEMP> CRM_SEMP { get; set; }
        public virtual DbSet<DepositosAvances> DepositosAvances { get; set; }
        public virtual DbSet<DepositosAvancesMensual> DepositosAvancesMensual { get; set; }
        public virtual DbSet<documentosCorte> documentosCorte { get; set; }
        public virtual DbSet<efectivoCorte> efectivoCorte { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<NotasDePagoes> NotasDePagoes { get; set; }
        public virtual DbSet<NotasDePagoMensuals> NotasDePagoMensuals { get; set; }
        public virtual DbSet<NotasDesempenoAvances> NotasDesempenoAvances { get; set; }
        public virtual DbSet<NotasDesempenoAvancesMensual> NotasDesempenoAvancesMensual { get; set; }
        public virtual DbSet<NotasRefrendoAvances> NotasRefrendoAvances { get; set; }
        public virtual DbSet<NotasRefrendoAvancesMensual> NotasRefrendoAvancesMensual { get; set; }
        public virtual DbSet<PrestamosAvances> PrestamosAvances { get; set; }
        public virtual DbSet<PrestamosAvancesMensual> PrestamosAvancesMensual { get; set; }
        public virtual DbSet<prueba> prueba { get; set; }
        public virtual DbSet<remisiones> remisiones { get; set; }
        public virtual DbSet<RemisionesAvances> RemisionesAvances { get; set; }
        public virtual DbSet<RemisionesAvancesMensual> RemisionesAvancesMensual { get; set; }
        public virtual DbSet<RetirosAvances> RetirosAvances { get; set; }
        public virtual DbSet<RetirosAvancesMensual> RetirosAvancesMensual { get; set; }
        public virtual DbSet<SaldoEnCajas> SaldoEnCajas { get; set; }
        public virtual DbSet<SaldoEnVivoCajas> SaldoEnVivoCajas { get; set; }
        public virtual DbSet<Siglas_inventario> Siglas_inventario { get; set; }
        public virtual DbSet<StatusPromociones> StatusPromociones { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<abono> abono { get; set; }
        public virtual DbSet<almacenaje> almacenaje { get; set; }
        public virtual DbSet<anterior_abono> anterior_abono { get; set; }
        public virtual DbSet<Apartados> Apartados { get; set; }
        public virtual DbSet<Apartados_confg> Apartados_confg { get; set; }
        public virtual DbSet<ApartadosEspeciales> ApartadosEspeciales { get; set; }
        public virtual DbSet<ApartadosEspecialesConfig> ApartadosEspecialesConfig { get; set; }
        public virtual DbSet<ApartadosEspecialesInventario> ApartadosEspecialesInventario { get; set; }
        public virtual DbSet<artventas101> artventas101 { get; set; }
        public virtual DbSet<artventas201> artventas201 { get; set; }
        public virtual DbSet<artventas501> artventas501 { get; set; }
        public virtual DbSet<artventas901> artventas901 { get; set; }
        public virtual DbSet<Auditoria> Auditoria { get; set; }
        public virtual DbSet<auditoria_fisica> auditoria_fisica { get; set; }
        public virtual DbSet<auditoria_resumen> auditoria_resumen { get; set; }
        public virtual DbSet<autorizaciones_prestamos> autorizaciones_prestamos { get; set; }
        public virtual DbSet<auxiliar_puesto> auxiliar_puesto { get; set; }
        public virtual DbSet<borrorem> borrorem { get; set; }
        public virtual DbSet<CAJA_AUXILIAR> CAJA_AUXILIAR { get; set; }
        public virtual DbSet<calificacion_aud> calificacion_aud { get; set; }
        public virtual DbSet<clasificacion_cl> clasificacion_cl { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<CLON_APARTADOS> CLON_APARTADOS { get; set; }
        public virtual DbSet<CLON_contratos> CLON_contratos { get; set; }
        public virtual DbSet<CLONA> CLONA { get; set; }
        public virtual DbSet<CLONARTVENTAS> CLONARTVENTAS { get; set; }
        public virtual DbSet<CLONB> CLONB { get; set; }
        public virtual DbSet<clontabla> clontabla { get; set; }
        public virtual DbSet<comprobaciones> comprobaciones { get; set; }
        public virtual DbSet<comprobaciones_gastos> comprobaciones_gastos { get; set; }
        public virtual DbSet<Config_valores_plazos> Config_valores_plazos { get; set; }
        public virtual DbSet<contabilidad> contabilidad { get; set; }
        public virtual DbSet<contrato_conta> contrato_conta { get; set; }
        public virtual DbSet<Contrato_temporal> Contrato_temporal { get; set; }
        public virtual DbSet<CORREO> CORREO { get; set; }
        public virtual DbSet<costo_reimpresion> costo_reimpresion { get; set; }
        public virtual DbSet<depositos> depositos { get; set; }
        public virtual DbSet<depositos_tipo> depositos_tipo { get; set; }
        public virtual DbSet<descuentos_distintos> descuentos_distintos { get; set; }
        public virtual DbSet<documentos> documentos { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<Envios> Envios { get; set; }
        public virtual DbSet<estado_civil> estado_civil { get; set; }
        public virtual DbSet<EstadosRepublica> EstadosRepublica { get; set; }
        public virtual DbSet<EstatusApartado> EstatusApartado { get; set; }
        public virtual DbSet<EstatusContratos> EstatusContratos { get; set; }
        public virtual DbSet<EstatusInventarios> EstatusInventarios { get; set; }
        public virtual DbSet<ETQ_VENTA> ETQ_VENTA { get; set; }
        public virtual DbSet<FactCO> FactCO { get; set; }
        public virtual DbSet<FactCTR> FactCTR { get; set; }
        public virtual DbSet<factura_conta> factura_conta { get; set; }
        public virtual DbSet<facturas> facturas { get; set; }
        public virtual DbSet<fechasAU> fechasAU { get; set; }
        public virtual DbSet<gastos> gastos { get; set; }
        public virtual DbSet<GradoEstudios> GradoEstudios { get; set; }
        public virtual DbSet<HistorialinventarioPromocion> HistorialinventarioPromocion { get; set; }
        public virtual DbSet<INFS> INFS { get; set; }
        public virtual DbSet<interes> interes { get; set; }
        public virtual DbSet<interes_conta> interes_conta { get; set; }
        public virtual DbSet<inventariopromocion> inventariopromocion { get; set; }
        public virtual DbSet<Localidades> Localidades { get; set; }
        public virtual DbSet<marcas_localidad> marcas_localidad { get; set; }
        public virtual DbSet<MIX11> MIX11 { get; set; }
        public virtual DbSet<MIX12> MIX12 { get; set; }
        public virtual DbSet<Niveles_acceso> Niveles_acceso { get; set; }
        public virtual DbSet<Noticias_SEMP2013> Noticias_SEMP2013 { get; set; }
        public virtual DbSet<NotificacionesTelefonicas> NotificacionesTelefonicas { get; set; }
        public virtual DbSet<Nuevacaja> Nuevacaja { get; set; }
        public virtual DbSet<OpcionesVerificacion> OpcionesVerificacion { get; set; }
        public virtual DbSet<paises> paises { get; set; }
        public virtual DbSet<Pension> Pension { get; set; }
        public virtual DbSet<Plazos_prestamos> Plazos_prestamos { get; set; }
        public virtual DbSet<prestamos_poliza> prestamos_poliza { get; set; }
        public virtual DbSet<prom_aplica> prom_aplica { get; set; }
        public virtual DbSet<prom_aumento> prom_aumento { get; set; }
        public virtual DbSet<prom_descuento_interes> prom_descuento_interes { get; set; }
        public virtual DbSet<prom_ventas> prom_ventas { get; set; }
        public virtual DbSet<promocioncaja> promocioncaja { get; set; }
        public virtual DbSet<promociones> promociones { get; set; }
        public virtual DbSet<promociones_Activas> promociones_Activas { get; set; }
        public virtual DbSet<promocionesregalo> promocionesregalo { get; set; }
        public virtual DbSet<PRVyusuarios> PRVyusuarios { get; set; }
        public virtual DbSet<Puestos> Puestos { get; set; }
        public virtual DbSet<puntos_confg> puntos_confg { get; set; }
        public virtual DbSet<PuntosClientes> PuntosClientes { get; set; }
        public virtual DbSet<refrendo> refrendo { get; set; }
        public virtual DbSet<RegistroHuellas> RegistroHuellas { get; set; }
        public virtual DbSet<Reimpresiones> Reimpresiones { get; set; }
        public virtual DbSet<remate_inventarios> remate_inventarios { get; set; }
        public virtual DbSet<Respaldos> Respaldos { get; set; }
        public virtual DbSet<Retiros> Retiros { get; set; }
        public virtual DbSet<Saldos> Saldos { get; set; }
        public virtual DbSet<seguro> seguro { get; set; }
        public virtual DbSet<selcaja> selcaja { get; set; }
        public virtual DbSet<sexos> sexos { get; set; }
        public virtual DbSet<siglasempresa> siglasempresa { get; set; }
        public virtual DbSet<tabla_result> tabla_result { get; set; }
        public virtual DbSet<TASA_PRESTAMOS> TASA_PRESTAMOS { get; set; }
        public virtual DbSet<TEMP_AVALUO> TEMP_AVALUO { get; set; }
        public virtual DbSet<TEMP_AVALUO2> TEMP_AVALUO2 { get; set; }
        public virtual DbSet<tipos_localidad> tipos_localidad { get; set; }
        public virtual DbSet<TPavaluos> TPavaluos { get; set; }
        public virtual DbSet<transferencias> transferencias { get; set; }
        public virtual DbSet<TRFENTRADA> TRFENTRADA { get; set; }
        public virtual DbSet<VALOR_FACTORES> VALOR_FACTORES { get; set; }
        public virtual DbSet<VALOR_FACTORES_MAS> VALOR_FACTORES_MAS { get; set; }
        public virtual DbSet<vencidos> vencidos { get; set; }
    }
}
