//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siglas_inventario
    {
        public string sigla_inventario { get; set; }
        public string sigla_inventario1 { get; set; }
        public string sigla_inventario2 { get; set; }
        public string referencia_inventario { get; set; }
        public string referencia_inventario1 { get; set; }
        public string referencia_inventario2 { get; set; }
        public string inv_tipo { get; set; }
        public string inv_tipo1 { get; set; }
        public string inv_tipo2 { get; set; }
        public Nullable<int> inventario_inicial { get; set; }
        public string empresa { get; set; }
        public string sucursal { get; set; }
        public string sigla_suc { get; set; }
        public int Id { get; set; }
    }
}
