//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASA_PRESTAMOS
    {
        public int no_plazo { get; set; }
        public string Nombre_plazo { get; set; }
        public string porcentaje_de_prestamo { get; set; }
        public string tiempo_plazo { get; set; }
        public string no_repeticiones_cantidad { get; set; }
        public string tipo_de_repeticiones { get; set; }
        public string tasa_de_interes { get; set; }
        public string tipo_de_interes { get; set; }
        public string estatus_plazo { get; set; }
        public string Comentario_adicional { get; set; }
        public string Alta_por { get; set; }
        public Nullable<System.DateTime> Fecha_alta { get; set; }
    }
}
