//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_AVALUO2
    {
        public string Cantidad { get; set; }
        public string Descripcion { get; set; }
        public string Subdescripcion { get; set; }
        public string Condiciones { get; set; }
        public Nullable<decimal> Valor_prenda { get; set; }
        public string Detalles_de_prenda { get; set; }
        public string Penalizado_con { get; set; }
        public string Plazo { get; set; }
        public Nullable<decimal> Prestamo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string alta_por { get; set; }
        public string folio { get; set; }
        public int no { get; set; }
        public Nullable<decimal> A { get; set; }
        public Nullable<decimal> B { get; set; }
        public string tipo { get; set; }
        public string modelo { get; set; }
        public string noserie { get; set; }
    }
}
