//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPavaluos
    {
        public int no { get; set; }
        public string definicion { get; set; }
        public string descripcion { get; set; }
        public string logo { get; set; }
        public string Su_avaluo_sera { get; set; }
        public string alta { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<int> premate { get; set; }
        public Nullable<decimal> desc_primero { get; set; }
        public Nullable<int> sremate { get; set; }
        public Nullable<decimal> desc_segundo { get; set; }
        public Nullable<int> remate { get; set; }
        public Nullable<decimal> limite_precio { get; set; }
        public Nullable<int> limite_refrendo { get; set; }
        public Nullable<decimal> limiteDescuentoVenta { get; set; }
        public Nullable<decimal> limiteDescuentoVentaJefe { get; set; }
        public Nullable<decimal> limiteDescuentoVentaCajero { get; set; }
        public Nullable<decimal> desc_tercero { get; set; }
        public string descPrimerPesos { get; set; }
        public string descSegundoPesos { get; set; }
        public string descTerceroPesos { get; set; }
    }
}
