//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudSemp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALOR_FACTORES_MAS
    {
        public int No_Factor { get; set; }
        public string Nombre_Factor { get; set; }
        public string Porcentaje_a_considerar { get; set; }
        public string Estatus_del_Factor { get; set; }
    }
}
